/// Flutter icons VainIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  VainIcons
///      fonts:
///       - asset: fonts/VainIcons.ttf
///
/// 
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
///
import 'package:flutter/widgets.dart';

class VainIcons {
  VainIcons._();

  static const _kFontFam = 'VainIcons';
  static const _kFontPkg = null;

  static const IconData plan = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData food_and_restaurant = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tray = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tray_black = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bar = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData breakfast = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diner = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData food_for_check_cal_val = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData technology = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData viewclients = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData recipe = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData event = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData recipe_1 = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_edit = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_full = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
